import { Producto } from './Productos';

export const HERRAMIENTAS_MANUALES: Producto[] = [
  {
    nombre: 'Cepillo de carpintero',
    marca: 'Tramontina',
    proveedor: 'Maderas Norte',
    precio: 9000,
    stock: 30,
    portada: 'assets/img/cepillo.jpg',
  },
  {
    nombre: 'Serrucho dentado',
    marca: 'Stanley',
    proveedor: 'Ferremundo',
    precio: 5000,
    stock: 45,
    portada: 'assets/img/serrucho.jpg',
  },
  {
    nombre: 'Formón de acero',
    marca: 'Bahco',
    proveedor: 'ToolStore',
    precio: 3200,
    stock: 60,
    portada: 'assets/img/formon.jpg',
  },
  {
    nombre: 'Lima plana',
    marca: 'Nicholson',
    proveedor: 'Ferremas',
    precio: 2700,
    stock: 75,
    portada: 'assets/img/lima.jpg',
  },
  {
    nombre: 'Mazo de goma',
    marca: 'Irwin',
    proveedor: 'Herracentro',
    precio: 4300,
    stock: 20,
    portada: 'assets/img/mazo.jpg',
  },
  {
    nombre: 'Cepillo de alambre',
    marca: 'Genérica',
    proveedor: 'ToolMarket',
    precio: 2100,
    stock: 100,
    portada: 'assets/img/cepillo_alambre.jpg',
  },
  {
    nombre: 'Pinza universal',
    marca: 'Trupper',
    proveedor: 'Ferretería Central',
    precio: 4800,
    stock: 90,
    portada: 'assets/img/pinza.jpg',
  },
  {
    nombre: 'Destornillador plano',
    marca: 'Stanley',
    proveedor: 'FerrePro',
    precio: 1900,
    stock: 200,
    portada: 'assets/img/destornillador.jpg',
  },
  {
    nombre: 'Prensa para madera',
    marca: 'Genérica',
    proveedor: 'Ferretería',
    precio: 10000,
    stock: 50,
    portada: 'assets/img/prensa.jpg',
  },
];

export const HERRAMIENTAS_ELECTRICAS: Producto[] = [
  {
    nombre: 'Cepillo eléctrico de carpintero',
    marca: 'Makita',
    proveedor: 'ToolCenter',
    precio: 32000,
    stock: 15,
    portada: 'assets/img/cepillo_electrico.jpg',
  },
  {
    nombre: 'Sierra circular',
    marca: 'DeWalt',
    proveedor: 'ProTools',
    precio: 42000,
    stock: 12,
    portada: 'assets/img/sierra.jpg',
  },
  {
    nombre: 'Lijadora orbital',
    marca: 'Bosch',
    proveedor: 'ToolCenter',
    precio: 25500,
    stock: 25,
    portada: 'assets/img/lijadora.jpg',
  },
  {
    nombre: 'Taladro percutor',
    marca: 'Black & Decker',
    proveedor: 'Ferremundo',
    precio: 31500,
    stock: 40,
    portada: 'assets/img/taladro.jpg',
  },
  {
    nombre: 'Fresadora (Router)',
    marca: 'Makita',
    proveedor: 'Maderas Norte',
    precio: 54000,
    stock: 10,
    portada: 'assets/img/router.jpg',
  },
  {
    nombre: 'Pistola de calor',
    marca: 'Einhell',
    proveedor: 'Herracentro',
    precio: 18500,
    stock: 22,
    portada: 'assets/img/pistola_calor.jpg',
  },
];

export const HERRAMIENTAS_INDUSTRIALES: Producto[] = [
  {
    nombre: 'Cepilladora de carpintero',
    marca: 'Makita',
    proveedor: 'ToolCenter',
    precio: 78000,
    stock: 8,
    portada: 'assets/img/cepilladora.jpg',
  },
  {
    nombre: 'Garlopa profesional',
    marca: 'DeWalt',
    proveedor: 'ProTools',
    precio: 67000,
    stock: 12,
    portada: 'assets/img/garlopa.jpg',
  },
  {
    nombre: 'Sierra industrial',
    marca: 'Bosch',
    proveedor: 'Ferremundo',
    precio: 88000,
    stock: 7,
    portada: 'assets/img/sierra_industrial.jpg',
  },
  {
    nombre: 'Lijadora de banda',
    marca: 'Einhell',
    proveedor: 'Herracentro',
    precio: 32000,
    stock: 15,
    portada: 'assets/img/lijadora_banda.jpg',
  },
  {
    nombre: 'Taladro de banco',
    marca: 'Black & Decker',
    proveedor: 'ToolMarket',
    precio: 46000,
    stock: 10,
    portada: 'assets/img/taladro_banco.jpg',
  },
  {
    nombre: 'Router/Fresadora',
    marca: 'Makita',
    proveedor: 'Maderas Norte',
    precio: 54000,
    stock: 9,
    portada: 'assets/img/router_fresadora.jpg',
  },
];

